### ISSUE TITLE
Adopt JavaScript for basic tailwindcss components

### ISSUE THREAD

**Issue by malcolmsparks** [juxt/card#1]
There are some layout components such as menu bars where copying the JSX from a tailwind site and converting to Hiccup syntax is laborious. It would be nice to be able to simply copy in some JSX and some JS React code from Tailwind community sites.

We want to continue with Tailwind, at least for now, but make it easier to import components. We also want to keep using ClojureScript and re-frame for state management aspects, and for general coding.

This issue probably involves some research in bringing in JSX into our shadow-cljs development environment, as explained here: https://shadow-cljs.github.io/docs/UsersGuide.html#_javascript_dialects

**Comment by armincerf** [comment]
Think this counts as done now
